### ISSUE TITLE
Refactor user-specification of outer tree

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/twt#107]
We currently allow users to bypass outer tree simulation by specifying Compartment source and branching times in the YAML file.  However there are some remaining issues:
* We have not tested the setting of unsampled Compartments as sources - currently Compartment objects generated from the YAML default to `unsampled=FALSE`.
* This is an unwieldy method for large transmission trees (manually entering a large number of Compartments in YAML)

We have a function called `eventlog.from.tree` that initializes an EventLogger object from a Newick tree string with a sequence of transmission events.  However it is still up to the user to pair this EventLogger object with a compatible Model object where the Compartment names match.  This has some limitations as illustrated by #105 - it was not apparent that the user has to specify unsampled Compartment objects corresponding to internal nodes of the transmission tree.

Using a Newick tree string confers some benefits.  It is a compact representation of transmission events and it describes the Compartment names, sources and branching times.  However, it cannot currently be used to assign CompartmentTypes, and it does not describe the number of lineages sampled per Compartment. We have two options:
1. deprecate Newick tree strings and require the user to write YAML
2. use Newick tree strings for sources and branching times only.  YAML must match all compartment names.

**Comment by ArtPoon** [comment]
@davidchampredon

**Comment by davidchampredon** [comment]
Here are my 2 cents... 

From the user's viewpoint, I think `twt` should have a _single_ file to specify the outer tree. More than one file will increase the risk of mistakes by users and development efforts for the upstream piece of code that generates the outer tree.

What we need to specify the outer tree in `twt` is more than what a standard Newick format could provide. The advantage of using a Newick string is its ubiquity and I think we lose this benefit as soon as we customize it.  

So, I vote for **one single YAML file to specify the outer tree**.
