### ISSUE TITLE
Inner tree plot error

### ISSUE THREAD

**Issue by RouxCil** [PoonLab/twt#121]
The inner tree plot function is not working using the README example (om master branch). 

Error message is:
Error in plot.window(...) : need finite 'ylim' values

**Comment by ArtPoon** [comment]
Reproduced.  It's something I changed in the `.layout.rect` function in `ggfree`.  Working on it.

**Comment by RouxCil** [comment]
Issue seems to still be there after a ggfree update

**Comment by ArtPoon** [comment]
Fixed in ggfree master branch.  Please pull and try again.

**Comment by RouxCil** [comment]
Working
