### ISSUE TITLE
Plotting results

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/twt#42]
There are at least three plots that we want to be able to generate from simulation results:
1. The population trajectories of CompartmentTypes
2. The outer (transmission) tree
3. The inner (coalescent) tree
Presently we are operating on an event logger class object.  What should happen if we call `plot(logger)`?  Should we implement different `plot` functions for this class?

**Comment by gtng92** [comment]
Current implementation:
```R
plot.Eventlogger(e, transmissions=F, migrations=F, node.labels=F)
```
If we call `plot(e)` where e is an EventLogger object, it converts first to an ape::phylo object before plotting. The default parameters exclude plotting migration and transmission events. The minimum set of events this function plots is all the coalescent events of the inner tree, but currently no plotting function created to generate strictly the outer transmission tree.

**Comment by ArtPoon** [comment]
Closing.  Open new issue to remind us to implement plot function for outer tree simulations.
